config/routes.rb
Rails.application.routes.draw do
  get 'page/index'
  root to: 'page#index'

  resources :transactions
  resources :users
  resources :co_ops
  resources :loans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/co_op.rb
# == Schema Information
#
# Table name: co_ops
#
#  id                 :bigint(8)        not null, primary key
#  phase_id           :integer          not null
#  is_active          :boolean          not null
#  name               :string(255)      not null
#  start_date         :datetime
#  end_date           :datetime
#  location           :string(255)
#  interest           :integer
#  initial_balance    :integer
#  expected_repayment :integer
#  current_balance    :integer
#

class CoOp < ApplicationRecord
  has_many :users
  belongs_to :phase
end

app/models/loan.rb
# == Schema Information
#
# Table name: loans
#
#  id         :bigint(8)        not null, primary key
#  user_id    :integer          not null
#  balance    :integer          not null
#  interest   :integer          not null
#  loan_start :datetime         not null
#  loan_end   :datetime         not null
#  created_at :datetime
#  updated_at :datetime
#

class Loan < ApplicationRecord
  belongs_to :user
  has_many :transactions

  validates :user_id, :balance, :loan_start, :loan_end, :interest, presence: true
end

app/models/phase.rb
# == Schema Information
#
# Table name: phases
#
#  id         :bigint(8)        not null, primary key
#  phase_type :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Phase < ApplicationRecord
  validates :phase_type, presence: true
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id         :bigint(8)        not null, primary key
#  role_name  :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Role < ApplicationRecord
  has_many :users

  validates :role_name, presence: true, uniqueness: true
end

app/models/saving.rb
# == Schema Information
#
# Table name: savings
#
#  id         :bigint(8)        not null, primary key
#  user_id    :integer          not null
#  balance    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Saving < ApplicationRecord
  belongs_to :user
  has_many :transactions

  validates :user_id, :balance, presence: true
end

app/models/transaction.rb
# == Schema Information
#
# Table name: transactions
#
#  id               :bigint(8)        not null, primary key
#  loan_id          :integer
#  saving_id        :integer
#  amount           :integer          not null
#  previous_balance :integer
#  new_balance      :integer
#  user_id          :integer          not null
#  created_at       :datetime
#  updated_at       :datetime
#  aasm_state       :string(255)
#

# require 'aasm'
class Transaction < ApplicationRecord
  # include AASM

  belongs_to :loan, optional: true
  belongs_to :saving, optional: true
  belongs_to :user

  # after_validation :set_balances

  validates :user_id, :amount, presence: true
  validate :loan_or_saving_present

  after_commit :set_balances, :update_user, on: :create

  # aasm whiny_transitions: false do
  #   state :pending, initial: true
  #   state :confirmed
  #
  #   event :confirm do
  #     transitions from: :pending, to: :confirmed
  #   end
  # end

  private

  def loan_or_saving_present
    return if (loan_id || saving_id).present?
    # TODO: add error
  end

  def set_balances
    self.previous_balance ||= loan.try(:balance) || saving.try(:balance)
    self.new_balance ||= previous_balance - amount
  end

  def update_user
    # loan.present? ? loan.balance = new_balance : saving.balance = new_balance
    # send confrimation of update back to co-op
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/co_ops_controller.rb
class CoOpsController < ApplicationController
  def index
    @co_ops = CoOp.all
  end

  def show
    @co_op = CoOp.find(params[:id])
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def index
    puts 'Loans index'
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    puts 'transactions index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    puts 'users index'
    @members = User.not_admin
  end

  def show
    @member = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link_to(text = nil, path = nil, options = nil, &block)
    given_path = block_given? && text.present? ? text : path
    active     = given_path =~ /#{request.path}/ || request.path =~ /#{given_path}/ ? 'active' : ''
    content_tag :li, class: active do
      link_to text, path, options, &block
    end
  end
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/co_ops/index.html.slim
h1 Co-ops
.table-responsive
    table.table.table-striped
        thead
            tr
                th class='col-sm-1' Name
                th class='col-sm-1' Location
                th class='col-sm-1' Users
                th class='col-sm-1' Start Date
                th class='col-sm-1' End Date
                th class='col-sm-1' Initial Balance
                th class='col-sm-1' Current Balance

        tbody
        - @co_ops.each do |co_op| 
            tr
                td= link_to co_op.name, co_op_path(co_op.id)
                td= co_op.location
                td= co_op.users.count
                td= co_op.start_date.strftime('%d/%m/%y')
                td= co_op.end_date.strftime('%d/%m/%y')
                td= co_op.initial_balance
                td= co_op.current_balance
        

app/views/co_ops/show.html.slim
h3.text-center= @co_op.name

.col-md-6
  dl.dl-horizontal
    dt Location
    dd= @co_op.location
    dt Users
    - @co_op.users.each do |user|
      dd= link_to user.full_name, user_path(user.id)
.col-md-6
  dl.dl-horizontal
    dt Start Date
    dd= @co_op.start_date.strftime('%d/%m/%y')
    dt End Date
    dd= @co_op.end_date.strftime('%d/%m/%y')
    dt Initial Balance
    dd= @co_op.initial_balance
    dt Current Balance
    dd= @co_op.current_balance

app/views/layouts/_environment.html.slim
- unless Rails.env.production?
  .container-fluid class="environment-warning #{Rails.env}"
    .row
      .col-lg-12.text-center
        .warning You are looking at #{Rails.env.upcase}

app/views/layouts/_head.html.slim
head
  title Pangea Network Admin Dashboard
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  

app/views/loans/index.html.slim
h1 Loans

app/views/page/index.html.slim
.row
  =link_to co_ops_path
    .col-sm-4.dashboard_box
      #co_ops
        h4= 'Co-Ops'
        h1.text-center= CoOp.count

  =link_to users_path
    .col-sm-4.dashboard_box
      #users
        h4= 'Users'
        h1.text-center= User.count

.row
  =link_to transactions_path
    .col-sm-4.dashboard_box
      #transactions
        h4= 'Transactions'
        h1.text-center= Transaction.count

  =link_to loans_path
    .col-sm-4.dashboard_box
      #co_ops
        h4= 'Loans'
        h1.text-center= Loan.count

app/views/transactions/index.html.slim
h1 Transactions

app/views/users/index.html.slim
h1 Members
.table-responsive
  table.table.table-striped
    thead
      tr
        th class='col-sm-1' Name
        th class='col-sm-1' Co Op
        th class='col-sm-1' Phone
        th class='col-sm-1' Role
        th class='col-sm-1' Loan Balance

    tbody
    - @members.each do |member|
      tr
        td= link_to member.full_name, user_path(member.id)
        td= member.co_op.name
        td= member.phone
        td= member.role.role_name.titleize
        td= member.loan.try(:balance) || '0'